using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Animation;
using CommunityToolkit.Mvvm.Messaging;
using StudentManagemantSystem.ViewModels;
using Wpf.Ui.Appearance;
using Wpf.Ui.Common;
using Wpf.Ui.Controls;

namespace StudentManagemantSystem;

/// <summary>
/// Interaction logic for MainWindow.xaml
/// </summary>
public partial class MainWindow : UiWindow, IRecipient<string>
{
    #region Public Constructors

    public MainWindow(MainWindowViewModel viewModel)
    {
        InitializeComponent();
        DataContext = this;
        Loaded += OnMainWindowLoaded;
        ViewModel = viewModel;
        ViewModel.SnackbarService.SetSnackbarControl(Snackbar);
        _navigateButtons = new()
        {
            StudentsNavigateButton,
            ClassesNavigateButton,
            SchoolsNavigateButton
        };
        WeakReferenceMessenger.Default.Register(this);
    }

    #endregion Public Constructors

    #region Public Properties

    public MainWindowViewModel ViewModel { get; }

    #endregion Public Properties

    #region Public Methods

    public void Receive(string message)
    {
        if (message == "Saved")
            DataGrid.Items.Refresh();
    }

    #endregion Public Methods

    #region Private Fields

    readonly List<Button> _navigateButtons;

    #endregion Private Fields

    #region Private Methods

    private void OnMainWindowLoaded(object sender, RoutedEventArgs e)
    {
        OnThemeButtonClicked(sender, e);
        OnNavigateButtonClicked(StudentsNavigateButton, new());
    }

    private void OnDataGridAutoGeneratingColumn(object sender, System.Windows.Controls.DataGridAutoGeneratingColumnEventArgs e)
    {
        e.Column.Header = ((PropertyDescriptor)e.PropertyDescriptor).DisplayName;
    }
    private void OnNavigateButtonClicked(object sender, RoutedEventArgs e)
    {
        foreach (var button in _navigateButtons)
        {
            button.IconFilled = false;
            button.Background = Brushes.Transparent;
            button.Foreground = (Brush)App.Current.Resources["TextFillColorPrimaryBrush"];
        }
        if (sender is Button currentButton)
        {
            currentButton.Background = currentButton.MouseOverBackground;
            var animation = new ColorAnimation(Accent.SystemAccent, TimeSpan.FromSeconds(0.2));
            var storyboard = new Storyboard();
            storyboard.Children.Add(animation);
            Storyboard.SetTarget(currentButton, animation);
            Storyboard.SetTargetProperty(animation, new("Foreground.Color"));
            storyboard.Begin(currentButton);
            currentButton.IconFilled = true;
            ViewModel.EntityTypeName = (string)currentButton.Tag;
            ViewModel.Refresh();
            DataGrid.SetBinding(System.Windows.Controls.ItemsControl.ItemsSourceProperty, string.Join('.', nameof(ViewModel), $"{ViewModel.EntityTypeName}Collection"));
            DataGrid.Items.Refresh();
        }
    }

    private void OnDataGridAutoGeneratedColumns(object sender, EventArgs e)
    {
        DataGrid.Columns[0].IsReadOnly = true;
        foreach (var column in DataGrid.Columns)
        {
            var header = (string)column.Header;
            if (header.Contains("集合"))
                column.Visibility = Visibility.Collapsed;
            else if (header.Contains("所属") && header.Contains("名称"))
                column.IsReadOnly = true;
        }
    }
    private void OnSelectionChanged(object sender, System.Windows.Controls.SelectionChangedEventArgs e)
    {
        if (ViewModel.IsNotBusy)
            ViewModel.SelectedItems = DataGrid.SelectedItems.Count == 0 ? default : DataGrid.SelectedItems;
    }

    private void OnThemeButtonClicked(object sender, RoutedEventArgs e)
    {
        if (Theme.GetAppTheme() == ThemeType.Light)
        {
            Theme.Apply(ThemeType.Dark, WindowBackdropType, true, true);
            ThemeButton.Icon = SymbolRegular.WeatherSunny24;
        }
        else
        {
            Theme.Apply(ThemeType.Light, WindowBackdropType, true, true);
            ThemeButton.Icon = SymbolRegular.WeatherMoon24;
        }
    }

    #endregion Private Methods
}
